
/* Drop Tables */

DROP TABLE DBCH_INSTALLATION_LOG CASCADE CONSTRAINTS;
DROP TABLE DBCH_INSTALLED_FRAGMENT CASCADE CONSTRAINTS;
DROP TABLE DBCH_FRAGMENT CASCADE CONSTRAINTS;
DROP TABLE DBCH_REQUIREMENT CASCADE CONSTRAINTS;
DROP TABLE DBCH_INSTALLATION CASCADE CONSTRAINTS;
DROP TABLE DBCH_DBCHANGE CASCADE CONSTRAINTS;
DROP TABLE DBCH_USERGROUP CASCADE CONSTRAINTS;
DROP TABLE DBCH_PLACEHOLDER CASCADE CONSTRAINTS;
DROP TABLE DBCH_USER CASCADE CONSTRAINTS;
DROP TABLE DBCH_ENVIRONMENT CASCADE CONSTRAINTS;
DROP TABLE DBCH_GROUP CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE DBCH_DBCH_SEQ;
DROP SEQUENCE DBCH_ENV_SEQ;
DROP SEQUENCE DBCH_FRAG_SEQ;
DROP SEQUENCE DBCH_G_SEQ;
DROP SEQUENCE DBCH_IF_SEQ;
DROP SEQUENCE DBCH_IL_SEQ;
DROP SEQUENCE DBCH_INST_SEQ;
DROP SEQUENCE DBCH_PLACE_SEQ;
DROP SEQUENCE DBCH_REQ_SEQ;
DROP SEQUENCE DBCH_UG_SEQ;
DROP SEQUENCE DBCH_USER_SEQ;




/* Create Sequences */

CREATE SEQUENCE DBCH_DBCH_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_ENV_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_FRAG_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_G_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_IF_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_IL_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_INST_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_PLACE_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_REQ_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_UG_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;
CREATE SEQUENCE DBCH_USER_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 10000000 START WITH 1;



/* Create Tables */

CREATE TABLE DBCH_DBCHANGE
(
	ID number(10) NOT NULL,
	CODE varchar2(20) NOT NULL UNIQUE,
	DESCRIPTION varchar2(200),
	PRIMARY KEY (ID)
);


CREATE TABLE DBCH_ENVIRONMENT
(
	ID number(10) NOT NULL,
	CODE varchar2(20) NOT NULL UNIQUE,
	NAME varchar2(100),
	DESCRIPTION varchar2(200),
	VERSION varchar2(20),
	PRIMARY KEY (ID)
);


CREATE TABLE DBCH_FRAGMENT
(
	ID number(10) NOT NULL,
	DBCHANGE_ID number(10) NOT NULL,
	GROUP_ID number(10) NOT NULL,
	TEMPLATECONTENT clob NOT NULL,
	INDEX_NUMBER number(4,0) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FRAGMENT_INDEX_U UNIQUE (DBCHANGE_ID, INDEX_NUMBER)
);


CREATE TABLE DBCH_GROUP
(
	ID number(10) NOT NULL,
	NAME varchar2(100) NOT NULL UNIQUE,
	IS_MANUAL number(1) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE DBCH_INSTALLATION
(
	ID number(10) NOT NULL,
	ENVIRONMENT_ID number(10) NOT NULL,
	DBCHANGE_ID number(10) NOT NULL,
	CREATED_AT timestamp,
	CREATED_BY varchar2(50) NOT NULL,
	STATUS number(1) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE DBCH_INSTALLATION_LOG
(
	ID number(10) NOT NULL,
	INSTALLATION_ID number(10) NOT NULL,
	INSTALLED_FRAGMENT_ID number(10) NOT NULL,
	INSTALLATION_STATUS number(1) NOT NULL,
	INSTALLED_FRAGMENT_STATUS number(1) NOT NULL,
	CONTENT clob NOT NULL,
	CREATED_AT timestamp NOT NULL,
	CREATED_BY varchar2(50) NOT NULL,
	RESULT_MESSAGE clob,
	PRIMARY KEY (ID)
);


CREATE TABLE DBCH_INSTALLED_FRAGMENT
(
	ID number(10) NOT NULL,
	INSTALLATION_ID number(10) NOT NULL,
	FRAGMENT_ID number(10) NOT NULL,
	USERGROUP_ID number(10) NOT NULL,
	DONE_AT timestamp,
	CONTENT clob NOT NULL,
	STATUS number(1) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE DBCH_PLACEHOLDER
(
	ID number(10) NOT NULL,
	ENVIRONMENT_ID number(10) NOT NULL,
	CODE varchar2(100) NOT NULL,
	TRANSLATED_VALUE varchar2(100) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT DBCH_PLACEHOLDER_ENVCODE_U UNIQUE (ENVIRONMENT_ID, CODE)
);


CREATE TABLE DBCH_REQUIREMENT
(
	ID number(10) NOT NULL,
	DBCHANGE_ID number(10) NOT NULL,
	REQUIRED_DBCHANGE_ID number(10) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT REQUIREMENT_U UNIQUE (DBCHANGE_ID, REQUIRED_DBCHANGE_ID)
);


CREATE TABLE DBCH_USER
(
	ID number(10) NOT NULL,
	ENVIRONMENT_ID number(10) NOT NULL,
	NAME varchar2(100) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT DBCH_USER_ENV_NAME_U UNIQUE (ENVIRONMENT_ID, NAME)
);


CREATE TABLE DBCH_USERGROUP
(
	ID number(10) NOT NULL,
	GROUP_ID number(10) NOT NULL,
	USER_ID number(10) NOT NULL,
	ENVIRONMENT_ID number(10) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT ENVUSERGROUP_U UNIQUE (GROUP_ID, USER_ID, ENVIRONMENT_ID)
);



/* Create Foreign Keys */

ALTER TABLE DBCH_FRAGMENT
	ADD CONSTRAINT FK_DBCH_FRAG_DBCH FOREIGN KEY (DBCHANGE_ID)
	REFERENCES DBCH_DBCHANGE (ID)
;


ALTER TABLE DBCH_REQUIREMENT
	ADD CONSTRAINT FK_DBCH_REQ_REQDBCH FOREIGN KEY (DBCHANGE_ID)
	REFERENCES DBCH_DBCHANGE (ID)
;


ALTER TABLE DBCH_REQUIREMENT
	ADD CONSTRAINT FK_DBCH_REQ_DBCH FOREIGN KEY (REQUIRED_DBCHANGE_ID)
	REFERENCES DBCH_DBCHANGE (ID)
;


ALTER TABLE DBCH_INSTALLATION
	ADD CONSTRAINT FK_DBCH_I_DBCHANGE FOREIGN KEY (DBCHANGE_ID)
	REFERENCES DBCH_DBCHANGE (ID)
;


ALTER TABLE DBCH_USERGROUP
	ADD CONSTRAINT FK_DBCH_UG_E FOREIGN KEY (ENVIRONMENT_ID)
	REFERENCES DBCH_ENVIRONMENT (ID)
;


ALTER TABLE DBCH_PLACEHOLDER
	ADD CONSTRAINT FK_DBCH_PLACE_E FOREIGN KEY (ENVIRONMENT_ID)
	REFERENCES DBCH_ENVIRONMENT (ID)
;


ALTER TABLE DBCH_INSTALLATION
	ADD CONSTRAINT FK_DBCH_I_ENV FOREIGN KEY (ENVIRONMENT_ID)
	REFERENCES DBCH_ENVIRONMENT (ID)
;


ALTER TABLE DBCH_USER
	ADD CONSTRAINT FK_DBCH_USER_E FOREIGN KEY (ENVIRONMENT_ID)
	REFERENCES DBCH_ENVIRONMENT (ID)
;


ALTER TABLE DBCH_INSTALLED_FRAGMENT
	ADD CONSTRAINT FK_DBCH_IF_FRAG FOREIGN KEY (FRAGMENT_ID)
	REFERENCES DBCH_FRAGMENT (ID)
;


ALTER TABLE DBCH_FRAGMENT
	ADD CONSTRAINT FK_DBCH_FRAG_G FOREIGN KEY (GROUP_ID)
	REFERENCES DBCH_GROUP (ID)
;


ALTER TABLE DBCH_USERGROUP
	ADD CONSTRAINT FK_DBCH_UG_G FOREIGN KEY (GROUP_ID)
	REFERENCES DBCH_GROUP (ID)
;


ALTER TABLE DBCH_INSTALLED_FRAGMENT
	ADD CONSTRAINT FK_DBCH_IF_I FOREIGN KEY (INSTALLATION_ID)
	REFERENCES DBCH_INSTALLATION (ID)
;


ALTER TABLE DBCH_INSTALLATION_LOG
	ADD CONSTRAINT FK_DBCH_IL_I FOREIGN KEY (INSTALLATION_ID)
	REFERENCES DBCH_INSTALLATION (ID)
;


ALTER TABLE DBCH_INSTALLATION_LOG
	ADD CONSTRAINT FK_DBCH_IL_IF FOREIGN KEY (INSTALLED_FRAGMENT_ID)
	REFERENCES DBCH_INSTALLED_FRAGMENT (ID)
;


ALTER TABLE DBCH_USERGROUP
	ADD CONSTRAINT FK_DBCH_UG_U FOREIGN KEY (USER_ID)
	REFERENCES DBCH_USER (ID)
;


ALTER TABLE DBCH_INSTALLED_FRAGMENT
	ADD CONSTRAINT FK_DBCH_IF_UG FOREIGN KEY (USERGROUP_ID)
	REFERENCES DBCH_USERGROUP (ID)
;


CREATE OR REPLACE TRIGGER "DBCH_E_sequence_insert"
BEFORE INSERT ON DBCH_ENVIRONMENT
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_ENV_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_INST_sequence_insert"
BEFORE INSERT ON DBCH_INSTALLATION
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_INST_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_IF_sequence_insert"
BEFORE INSERT ON DBCH_INSTALLED_FRAGMENT
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_IF_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_FRAG_sequence_insert"
BEFORE INSERT ON DBCH_FRAGMENT
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_FRAG_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_REQ_sequence_insert"
BEFORE INSERT ON DBCH_REQUIREMENT
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_REQ_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_DBCH_sequence_insert"
BEFORE INSERT ON DBCH_DBCHANGE
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_DBCH_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_UG_sequence_insert"
BEFORE INSERT ON DBCH_USERGROUP
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_UG_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_G_sequence_insert"
BEFORE INSERT ON DBCH_GROUP
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_G_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_USER_sequence_insert"
BEFORE INSERT ON DBCH_USER
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_USER_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_INST_created_at"
BEFORE INSERT ON DBCH_INSTALLATION
FOR EACH ROW
WHEN (new.CREATED_AT IS NULL)
  BEGIN
    SELECT SYSDATE INTO :new.CREATED_AT FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_IL_sequence_insert"
BEFORE INSERT ON DBCH_INSTALLATION_LOG
FOR EACH ROW
WHEN (new.ID IS NULL)
  BEGIN
    SELECT DBCH_IL_SEQ.NEXTVAL INTO :new.ID FROM dual;
  END;
/

CREATE OR REPLACE TRIGGER "DBCH_IL_created_at"
BEFORE INSERT ON DBCH_INSTALLATION_LOG
FOR EACH ROW
WHEN (new.CREATED_AT IS NULL)
  BEGIN
    SELECT SYSDATE INTO :new.CREATED_AT FROM dual;
  END;
/


