INSERT INTO TABLEFORVIEW (VALUE1, VALUE2) VALUES (1, 'val 1');
INSERT INTO TABLEFORVIEW (VALUE1, VALUE2) VALUES (1, 'val 2');
INSERT INTO TABLEFORVIEW (VALUE1, VALUE2) VALUES (1, 'val 3');

INSERT INTO TABLEFORVIEW (VALUE1, VALUE2) VALUES (2, 'val 4');
INSERT INTO TABLEFORVIEW (VALUE1, VALUE2) VALUES (2, 'val 5');
INSERT INTO TABLEFORVIEW (VALUE1, VALUE2) VALUES (2, 'val 6');
