CREATE OR REPLACE VIEW TESTEMPTYGLOBALVIEW AS
SELECT
	v.VALUE11 as ONEVALUE1, v.VALUE12 as ONEVALUE2, v.VALUE21 as TWOVALUE1, v.VALUE22 as TWOVALUE2, v.REGION as REGION FROM (
/*START*/ SELECT
          tone.VALUE1 as VALUE11, tone.VALUE2 as VALUE12, ttwo.VALUE1 as VALUE21, ttwo.VALUE2 as VALUE22, '<empty>' as REGION
        FROM
          <empty>.DUMMYTABLE tone, <empty>.DUMMYTABLE ttwo
        WHERE
          tone.VALUE1 = 1 AND
          ttwo.VALUE1 = 2
/*END*/
/*GLUE_START UNION ALL GLUE_END*/
) v;
