-- DELIMITER
CREATE OR REPLACE TRIGGER TESTTRIGGER_CREATED_AT_I
BEFORE UPDATE ON TESTTRIGGER
FOR EACH ROW
  BEGIN
    :new.CREATED_AT := sysdate;
  END;
/

-- DELIMITER
CREATE OR REPLACE TRIGGER TESTTRIGGER_CREATED_AT_I2
BEFORE UPDATE ON TESTTRIGGER
FOR EACH ROW
  BEGIN
    :new.CREATED_AT := sysdate;
  END;
/