-- DELIMITER
CREATE OR REPLACE TRIGGER TESTCENTRALTABLE_CREATED_AT_I
BEFORE INSERT ON TESTCENTRALTABLE
FOR EACH ROW
  BEGIN
    :new.CREATED_AT := sysdate;
  END;
/

-- DELIMITER
CREATE OR REPLACE TRIGGER TESTCENTRALTABLE_CREATED_AT_U
BEFORE UPDATE ON TESTCENTRALTABLE
FOR EACH ROW
  BEGIN
    :new.CREATED_AT := sysdate;
  END;
/