GRANT SELECT, INSERT, UPDATE, DELETE ON TESTCENTRALTABLE to <region> with grant option;
GRANT SELECT, INSERT, UPDATE, DELETE ON TESTCENTRALTABLE TO <user>;
GRANT ALL ON TESTCENTRALTABLE TO <systemuser>;
